/* Generated By:JJTree: Do not edit this line. ASTArg_List.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArg_List extends SimpleNode {
  public ASTArg_List(int id) {
    super(id);
  }

  public ASTArg_List(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a2323f445d1f715de38d6c2f8bcff49 (do not edit this line) */
