/* Generated By:JJTree: Do not edit this line. ASTConstant_Declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstant_Declaration extends SimpleNode {
  public ASTConstant_Declaration(int id) {
    super(id);
  }

  public ASTConstant_Declaration(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=60271b0827da71547d1848110211bedb (do not edit this line) */
