/* Generated By:JJTree: Do not edit this line. ASTNParamList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNParamList extends SimpleNode {
  public ASTNParamList(int id) {
    super(id);
  }

  public ASTNParamList(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=101f2422517b22aa6280cd56a3b02dcb (do not edit this line) */
