/* Generated By:JJTree: Do not edit this line. ASTVariable_Declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariable_Declaration extends SimpleNode {
  public ASTVariable_Declaration(int id) {
    super(id);
  }

  public ASTVariable_Declaration(CCAL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9285ee69e437f91fa4f6be6309f15acd (do not edit this line) */
