/* Generated By:JavaCC: Do not edit this line. CCALVisitor.java Version 5.0 */
public interface CCALVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVariable_Declaration node, Object data);
  public Object visit(ASTConstant_Declaration node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTNParamList node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTcomp node, Object data);
  public Object visit(ASTArg_List node, Object data);
}
/* JavaCC - OriginalChecksum=673cc37e25021026a6df64967754b4b0 (do not edit this line) */
