/* Generated By:JavaCC: Do not edit this line. CCALTreeConstants.java Version 5.0 */
public interface CCALTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIDENTIFIER = 1;
  public int JJTTYPE = 2;
  public int JJTNUMBER = 3;
  public int JJTVOID = 4;
  public int JJTVARIABLE_DECLARATION = 5;
  public int JJTCONSTANT_DECLARATION = 6;
  public int JJTFUNCTION = 7;
  public int JJTNPARAMLIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTCOMP = 11;
  public int JJTARG_LIST = 12;


  public String[] jjtNodeName = {
    "Program",
    "Identifier",
    "Type",
    "Number",
    "void",
    "Variable_Declaration",
    "Constant_Declaration",
    "Function",
    "NParamList",
    "Main",
    "Statement",
    "comp",
    "Arg_List",
  };
}
/* JavaCC - OriginalChecksum=740242c4f81f959d54916ca8d46b32a9 (do not edit this line) */
